import re

file_path = r'c:\Users\willi\AndroidStudioProjects\SkilldConect-main\documentacion\informe_skillconnect.tex'

with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

replacements = {
    r"\\subsection\{Pantalla de Carga \(Splash Screen\)\}\n% --------------------------------------------------\n(.*)\n\n\\begin\{figure\}":
    r"\\subsection{Pantalla de Carga (Splash Screen)}\n% --------------------------------------------------\nLa pantalla de carga inicial o Splash Screen es el primer punto de contacto entre el usuario y SkillConnect. Esta interfaz cumple un doble propósito: a nivel visual, presenta la identidad de la marca mediante un logotipo centrado con un efecto de pulsación (scale-down micro-animation) sobre un fondo limpio y minimalista. A nivel técnico, esta pantalla se encarga de inicializar los repositorios locales (Room Database), comprobar si existe un token de sesión activo en Firebase Authentication y pre-cargar los datos del perfil de usuario antes de redirigirlo automáticamente al Home o a la pantalla de Bienvenida si es su primera vez.\n\n\\begin{figure}",

    r"\\subsection\{Pantalla de Bienvenida \(Welcome\)\}\n% --------------------------------------------------\n(.*)\n\n\\begin\{figure\}":
    r"\\subsection{Pantalla de Bienvenida (Welcome)}\n% --------------------------------------------------\nEsta pantalla actúa como el Onboarding principal de la plataforma. Recibe al usuario con el eslogan central 'Todo el mundo tiene algo que enseñar y algo que aprender', reforzando la filosofía de aprendizaje bilateral de la app. Desde aquí, el usuario cuenta con accesos directos interactivos diseñados con botones Neumórficos (con sombras suaves que dan la ilusión de relieve) para iniciar sesión o registrar una nueva cuenta. La disposición de los elementos está calculada según la Ley de Fitts para facilitar el alcance del pulgar a los llamados a la acción (CTAs) principales.\n\n\\begin{figure}",

    r"\\subsection\{Inicio de Sesión y Registro\}\n% --------------------------------------------------\n(.*)\n\n\\begin\{figure\}":
    r"\\subsection{Inicio de Sesión y Registro}\n% --------------------------------------------------\nLos formularios de autenticación están diseñados para minimizar la fricción cognitiva. La pantalla de Inicio de Sesión permite el acceso rápido mediante correo y contraseña, integrando además una opción de recuperación de cuenta y soporte para inicio de sesión biométrico. Por su parte, la pantalla de Registro captura los datos esenciales del usuario y le permite definir inmediatamente su rol inicial dentro del ecosistema: 'Quiero aprender', 'Quiero enseñar', o 'Ambos'. Ambos formularios cuentan con validación reactiva en tiempo real, indicando errores de formato al instante mediante cambios de color sutiles en los bordes de los campos de texto y alertas (Toasts) informativos.\n\n\\begin{figure}",

    r"\\subsection\{Pantalla Principal \(Home\)\}\n% --------------------------------------------------\n(.*)\n\n\\begin\{figure\}":
    r"\\subsection{Pantalla Principal (Home)}\n% --------------------------------------------------\nEl Home o Dashboard es el núcleo operativo de SkillConnect. En la parte superior, presenta un cabezal personalizado con un gradiente premium 'Ocean Deep' que saluda al usuario por su nombre. Integra un buscador global flotante estilizado con efecto Glassmorphism (cristal esmerilado translúcido) para consultas rápidas. Además, incluye una tarjeta promocional dinámica que fomenta el 'Trueque de Habilidades', y una grilla interactiva (Grid) de categorías populares (Programación, Idiomas, Arte, etc.) representadas por íconos de Material Design. Cada elemento de esta pantalla responde al tacto con físicas de resorte (spring animations), hundiéndose suavemente al ser presionado.\n\n\\begin{figure}",

    r"\\subsection\{Búsqueda y Perfil del Mentor\}\n% --------------------------------------------------\n(.*)\n\n\\begin\{figure\}":
    r"\\subsection{Búsqueda y Perfil del Mentor}\n% --------------------------------------------------\nEl módulo de búsqueda avanzada permite a los usuarios filtrar mentores y habilidades específicas en tiempo real, conectándose con la base de datos de perfiles. Al seleccionar un resultado, se despliega el Perfil del Mentor (Experto). Esta pantalla detallada muestra una cabecera con la foto del mentor, su tarifa por hora (Booking) o disponibilidad para trueque, su calificación promedio mediante un sistema de estrellas y reseñas, así como una lista horizontal (LazyRow) con las habilidades exactas que domina. Desde aquí, el estudiante puede iniciar directamente una solicitud de clase o enviar un mensaje privado.\n\n\\begin{figure}",

    r"\\subsection\{Reserva de Clases y Trueque\}\n% --------------------------------------------------\n(.*)\n\n\\begin\{figure\}":
    r"\\subsection{Reserva de Clases y Trueque}\n% --------------------------------------------------\nSkillConnect soporta dos modelos de interacción paralelos. Por un lado, la pantalla de Solicitud de Trueque (Exchange) presenta un formulario donde el usuario ofrece una de sus habilidades a cambio de aprender una del mentor, proponiendo un horario tentativo de mutuo beneficio sin intercambio monetario. Por otro lado, la pantalla de Reserva de Clases (Booking) maneja el modelo tradicional: permite seleccionar una fecha específica en un calendario interactivo integrado, elegir la duración de la sesión y confirmar la clase, generando automáticamente un evento pendiente en la base de datos local y alertando al mentor.\n\n\\begin{figure}",

    r"\\subsection\{Mensajería y Chat\}\n% --------------------------------------------------\n(.*)\n\n\\begin\{figure\}":
    r"\\subsection{Mensajería y Chat}\n% --------------------------------------------------\nPara facilitar la comunicación directa, la app cuenta con un completo sistema de mensajería nativa. La Bandeja de Entrada (Messages) lista todas las conversaciones activas, mostrando el último mensaje enviado, la hora y un indicador visual de mensajes no leídos (badges). Al ingresar a una conversación, la pantalla de Chat ofrece una interfaz estilo burbuja (bubble chat) separando visualmente los mensajes enviados y recibidos mediante colores de la paleta principal (Azul y Teal). El chat interactúa con Cloud Firestore para garantizar la entrega de mensajes en tiempo real y utiliza Room para guardar el historial y permitir lectura sin conexión (offline).\n\n\\begin{figure}",

    r"\\subsection\{Agenda y Notificaciones\}\n% --------------------------------------------------\n(.*)\n\n\\begin\{figure\}":
    r"\\subsection{Agenda y Notificaciones}\n% --------------------------------------------------\nLa organización del tiempo es clave en el aprendizaje. La pantalla de Agenda y Citas despliega un calendario interactivo donde se visualizan los compromisos del usuario, clasificados dinámicamente mediante pestañas (Tabs) en: Clases, Mentorías e Intercambios. Cada evento muestra la hora, la habilidad a tratar y el contacto. Adicionalmente, el Centro de Solicitudes y Alertas (Notificaciones) centraliza todas las interacciones entrantes: avisos de nuevos mensajes, confirmaciones de reservas de clase y aceptaciones de trueques, permitiendo al usuario tomar acciones directas desde la misma lista (Aceptar/Rechazar).\n\n\\begin{figure}",

    r"\\subsection\{Gestión de Habilidades y Aprendizaje\}\n% --------------------------------------------------\n(.*)\n\n\\begin\{figure\}":
    r"\\subsection{Gestión de Habilidades y Aprendizaje}\n% --------------------------------------------------\nEl área de gestión académica personal se divide en dos secciones vitales. La pantalla 'Mis Habilidades' permite al usuario administrar su propio portafolio de enseñanza, añadiendo nuevas disciplinas, definiendo su nivel de experiencia y gestionando las reseñas recibidas como mentor. En contraste, la pantalla 'Mis Aprendizajes' actúa como un panel de seguimiento para el rol de estudiante, mostrando el progreso de los cursos o mentorías que el usuario está recibiendo actualmente, las horas invertidas y las próximas sesiones programadas.\n\n\\begin{figure}",

    r"\\subsection\{Mi Perfil y Estadísticas\}\n% --------------------------------------------------\n(.*)\n\n\\begin\{figure\}":
    r"\\subsection{Mi Perfil y Estadísticas}\n% --------------------------------------------------\nLa pantalla de Perfil centraliza la identidad y la configuración del usuario. Muestra de forma elegante el nivel alcanzado, la descripción personal y ofrece accesos directos a funciones administrativas. Para fomentar la retención y la motivación, se incluye un Panel de Estadísticas profundo que, a través de gráficos visuales generados dinámicamente, ilustra el progreso del usuario: número de horas enseñadas, habilidades aprendidas y la evolución de su calificación. Esta retroalimentación visual continua es fundamental para la retención en aplicaciones educativas modernas.\n\n\\begin{figure}",

    r"\\subsection\{Logros \(Gamificación\) y Configuración\}\n% --------------------------------------------------\n(.*)\n\n\\begin\{figure\}":
    r"\\subsection{Logros (Gamificación) y Configuración}\n% --------------------------------------------------\nAplicando principios de gamificación, la pantalla de Logros presenta un sistema de insignias (badges) que se desbloquean a medida que el usuario completa hitos (ej. 'Primer Trueque', 'Mentor de Excelencia', 'Estudiante Dedicado'). Estas insignias se guardan de manera persistente y sirven como prueba social del compromiso del usuario. Por último, la pantalla de Configuración ofrece control total sobre la experiencia de la aplicación: alternancia al Modo Oscuro Neumórfico, gestión de notificaciones push, privacidad, y la opción avanzada de vincular la Huella Digital o reconocimiento facial (BiometricManager) para futuros accesos ultra-rápidos y seguros.\n\n\\begin{figure}"
}

for pattern, replacement in replacements.items():
    content = re.sub(pattern, replacement, content)

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)
print('Done!')
